<?php

/**
 * @file
 * Contains server.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function server_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the server module.
    case 'help.page.server':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Idc servers.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function server_theme() {
  return [
    'server' => [
      'render element' => 'children',
    ],
  ];
}
