<?php

/**
 * @file
 * Contains ultrix_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function ultrix_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ultrix_core module.
    case 'help.page.ultrix_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ultrix core') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ultrix_core_theme() {
  return [
    'ultrix_core' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ultrix_core_preprocess_menu__role_menu(&$variables) {
  $icons = [
    'ultrix_core.admin' => 'fa fa-cubes',
  ];

  _eabax_core_set_menu_items_icon($variables['items'], $icons);
}

/**
 * Implements hook_toolbar().
 */
function ultrix_core_toolbar() {
  $items = [];

  $items['ultrix_core'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Ultrix2'),
      '#url' => Url::fromRoute('ultrix_core.admin'),
      '#optionns' => [
        'attributes' => [
          'title' => t('Uc'),
          'class' => ['toolbar-icon', 'toolbar-icon-ultrix-admin'],
        ],
      ],
    ],
    '#weight' => 20,
  ];

  return $items;
}

