<?php

/**
 * @file
 * Contains ip.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ip_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ip module.
    case 'help.page.ip':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The IP management for Ultrix.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ip_theme() {
  return [
    'ip' => [
      'render element' => 'children',
    ],
  ];
}
